#!/usr/bin/python

from sys import exit
from httplib import HTTPSConnection
from json import loads

DEBUG = 0
HOST = 'graph.api.smartthings.com'

## This should be the URI for your SmartApp
URI = '/api/smartapps/installations/..."
API_KEY = 'Bearer XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXX'

headers = {'Authorization': API_KEY}

conn = HTTPSConnection(HOST, '443')
try:
    conn.request('GET', URI, {}, headers)
except:
    print "Error: could not connect to remote site"
    exit(-1)

conn.set_debuglevel(DEBUG)

res = conn.getresponse()

if (res.status != 200):
    conn.close()
    print "Error: received non-200 HTTP response (%d)" % res.status
    exit(-1)
else:
    data = res.read()
    conn.close()

js_data = loads(data)

present = 0

for sensor in js_data:
    if sensor['value'] == 'present':
        present = 1

exit(present)

