#!/usr/bin/python
#
# is_present -- Retrieve SmartThings presence sensor data
# Created: Marcus Butler <marcusb@marcusb.org>, 28-February-2017
#
# This script iterates over each presence sensor exposed by a companion
# SmartApp (see presenceList_smartapp) and returns 0 if all sensors are not
# present, 1 if any sensor is present, and -1 on error.
#

from sys import exit
from httplib import HTTPSConnection
from json import loads

### Configuration variables

DEBUG = 0 # Set to 10 to troubleshoot server issues
URI = '/api/smartapps/installations/...' # Set to the URI for your SmartApp
API_KEY = 'XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXX' # Set to your API key

### Configuration variables stop here

HOST = 'graph.api.smartthings.com'
headers = {'Authorization': 'Bearer %s' % API_KEY}

conn = HTTPSConnection(HOST, '443')
try:
    conn.request('GET', URI, {}, headers)
except:
    print "Error: could not connect to remote site"
    exit(-1)

conn.set_debuglevel(DEBUG)

res = conn.getresponse()

if (res.status != 200):
    conn.close()
    print "Error: received non-200 HTTP response (%d)" % res.status
    exit(-1)
else:
    data = res.read()
    conn.close()

js_data = loads(data)

present = 0

for sensor in js_data:
    if sensor['value'] == 'present':
        present = 1

exit(present)
